package com.ai.agent.skill;

public enum SkillRegistryErrorCode {
    SKILLS_ROOT_UNAVAILABLE,
    SKILL_FILE_READ_FAILED,
    SKILL_PATH_ESCAPE,
    SKILL_FRONTMATTER_MISSING,
    SKILL_FRONTMATTER_INVALID
}
